"""permissions

Revision ID: 12ca081ca938
Revises: 39d7d51619b2
Create Date: 2026-07-29 11:48:24.998837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ca081ca938'
down_revision: Union[str, Sequence[str], None] = '39d7d51619b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'INSTANCE', name='type'), nullable=False),
    sa.Column('system_feature', sa.Enum('ORGANIZATION', 'ROLES', 'USERS', 'SETTINGS', 'ORDERS', name='systemfeature'), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'CREATE', 'EDIT', 'DELETE', name='action'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'action', 'system_feature', 'instance_id', name='uc_type_action_system_feature_instance_id')
    )
    op.add_column('organization_users', sa.Column('role_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_users', 'role_id')
    op.drop_table('permissions')
    # ### end Alembic commands ###
