"""renamed enums

Revision ID: 2eb8cc7b7cc3
Revises: 4edd3623173d
Create Date: 2026-07-29 11:57:02.973575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb8cc7b7cc3'
down_revision: Union[str, Sequence[str], None] = '4edd3623173d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'INSTANCE', name='type'), nullable=False),
    sa.Column('system_feature', sa.Enum('ORGANIZATION', 'ROLE', 'USER', name='systemfeature'), nullable=True),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('VIEW', 'CREATE', 'EDIT', 'DELETE', name='action'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'action', 'system_feature', 'instance_id', name='uc_type_action_system_feature_instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
