"""nullable permission fields

Revision ID: 4edd3623173d
Revises: 12ca081ca938
Create Date: 2026-07-29 11:51:28.665050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4edd3623173d'
down_revision: Union[str, Sequence[str], None] = '12ca081ca938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'system_feature',
               existing_type=postgresql.ENUM('ORGANIZATION', 'ROLES', 'USERS', 'SETTINGS', 'ORDERS', name='systemfeature'),
               nullable=True)
    op.alter_column('permissions', 'instance_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'instance_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permissions', 'system_feature',
               existing_type=postgresql.ENUM('ORGANIZATION', 'ROLES', 'USERS', 'SETTINGS', 'ORDERS', name='systemfeature'),
               nullable=False)
    # ### end Alembic commands ###
