"""major role overhaul3

Revision ID: 67fc97113c4a
Revises: cc7dd6d0d12b
Create Date: 2026-08-02 08:15:42.481763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fc97113c4a'
down_revision: Union[str, Sequence[str], None] = 'cc7dd6d0d12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature', 'action', name='uc_feature_action')
    )
    op.create_table('system_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['system_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instance_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'action', name='uc_instance_action')
    )
    op.create_index(op.f('ix_instance_permissions_instance_id'), 'instance_permissions', ['instance_id'], unique=False)
    op.create_table('role_system_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('system_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['system_permission_id'], ['system_permissions.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'system_permission_id')
    )
    op.create_table('instance_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_permission_id', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instance_permission_id'], ['instance_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_user_instance_permission_override_id'), table_name='user_instance_permission_override')
    op.drop_table('user_instance_permission_override')
    op.drop_index(op.f('ix_user_permission_override_id'), table_name='user_permission_override')
    op.drop_table('user_permission_override')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_module_instances_id'), table_name='module_instances')
    op.add_column('role_instance_permissions', sa.Column('instance_permission_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_role_instance_permissions_instance_id'), table_name='role_instance_permissions')
    op.drop_constraint(op.f('role_instance_permissions_instance_id_fkey'), 'role_instance_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_instance_permissions', 'instance_permissions', ['instance_permission_id'], ['id'])
    op.drop_column('role_instance_permissions', 'instance_id')
    op.drop_column('role_instance_permissions', 'action')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('role_instance_permissions', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('role_instance_permissions', sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'role_instance_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_instance_permissions_instance_id_fkey'), 'role_instance_permissions', 'module_instances', ['instance_id'], ['id'])
    op.create_index(op.f('ix_role_instance_permissions_instance_id'), 'role_instance_permissions', ['instance_id'], unique=False)
    op.drop_column('role_instance_permissions', 'instance_permission_id')
    op.create_index(op.f('ix_module_instances_id'), 'module_instances', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('user_permission_override',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effect', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_permission_override_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_permission_override_pkey'))
    )
    op.create_index(op.f('ix_user_permission_override_id'), 'user_permission_override', ['id'], unique=False)
    op.create_table('user_instance_permission_override',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('effect', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_instance_permission_override_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_instance_permission_override_pkey'))
    )
    op.create_index(op.f('ix_user_instance_permission_override_id'), 'user_instance_permission_override', ['id'], unique=False)
    op.drop_table('instance_permission_override')
    op.drop_table('role_system_permissions')
    op.drop_index(op.f('ix_instance_permissions_instance_id'), table_name='instance_permissions')
    op.drop_table('instance_permissions')
    op.drop_table('system_permission_override')
    op.drop_table('system_permissions')
    # ### end Alembic commands ###
