"""removed database level enums everywhere cause enums in postgres is a headache

Revision ID: 7663b0e802d5
Revises: 4bdde8d5dbf1
Create Date: 2026-07-30 13:06:50.575023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7663b0e802d5'
down_revision: Union[str, Sequence[str], None] = '4bdde8d5dbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('system_feature', sa.String(), nullable=True),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'action', 'system_feature', 'instance_id', name='uc_type_action_system_feature_instance_id')
    )
    op.create_index(op.f('ix_permissions_instance_id'), 'permissions', ['instance_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_identifier', 'invited_by', name='unique_invite')
    )
    op.create_index(op.f('ix_invites_invited_by'), 'invites', ['invited_by'], unique=False)
    op.create_index(op.f('ix_invites_organization_id'), 'invites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_index(op.f('ix_invites_user_identifier'), 'invites', ['user_identifier'], unique=False)
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'user_permission_override', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permission_override', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_index(op.f('ix_invites_user_identifier'), table_name='invites')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_organization_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_invited_by'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_permissions_instance_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
