"""bug

Revision ID: a6ae7cee2680
Revises: 40987e3a9339
Create Date: 2026-07-30 10:44:25.426290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ae7cee2680'
down_revision: Union[str, Sequence[str], None] = '40987e3a9339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_invites_org_id'), table_name='invites')
    op.drop_constraint(op.f('unique_invite'), 'invites', type_='unique')
    op.create_unique_constraint('unique_invite', 'invites', ['organization_id', 'email', 'invited_by'])
    op.create_index(op.f('ix_invites_organization_id'), 'invites', ['organization_id'], unique=False)
    op.drop_constraint(op.f('invites_org_id_fkey'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invites', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_org_id_fkey'), 'invites', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_invites_organization_id'), table_name='invites')
    op.drop_constraint('unique_invite', 'invites', type_='unique')
    op.create_unique_constraint(op.f('unique_invite'), 'invites', ['org_id', 'email', 'invited_by'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_invites_org_id'), 'invites', ['org_id'], unique=False)
    op.drop_column('invites', 'organization_id')
    # ### end Alembic commands ###
