"""major role overhaul2

Revision ID: cc7dd6d0d12b
Revises: 7663b0e802d5
Create Date: 2026-08-01 18:43:05.909593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7dd6d0d12b'
down_revision: Union[str, Sequence[str], None] = '7663b0e802d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature', 'action', name='uc_feature_action')
    )
    op.create_table('user_instance_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('effect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_instance_permission_override_id'), 'user_instance_permission_override', ['id'], unique=False)
    op.create_table('module_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='unique_module_instance_name_organization')
    )
    op.create_index(op.f('ix_module_instances_id'), 'module_instances', ['id'], unique=False)
    op.create_index(op.f('ix_module_instances_organization_id'), 'module_instances', ['organization_id'], unique=False)
    op.create_table('role_instance_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['module_instances.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'instance_id', 'action')
    )
    op.create_index(op.f('ix_role_instance_permissions_instance_id'), 'role_instance_permissions', ['instance_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_foreign_key(None, 'user_permission_override', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permission_override', type_='foreignkey')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_instance_permissions_instance_id'), table_name='role_instance_permissions')
    op.drop_table('role_instance_permissions')
    op.drop_index(op.f('ix_module_instances_organization_id'), table_name='module_instances')
    op.drop_index(op.f('ix_module_instances_id'), table_name='module_instances')
    op.drop_table('module_instances')
    op.drop_index(op.f('ix_user_instance_permission_override_id'), table_name='user_instance_permission_override')
    op.drop_table('user_instance_permission_override')
    op.drop_table('permissions')
    # ### end Alembic commands ###
