"""rename invite/email to invite/user_idenntifier

Revision ID: fb7c554cf444
Revises: a6ae7cee2680
Create Date: 2026-07-30 11:12:01.861040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7c554cf444'
down_revision: Union[str, Sequence[str], None] = 'a6ae7cee2680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('user_identifier', sa.String(), nullable=False))
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_constraint(op.f('unique_invite'), 'invites', type_='unique')
    op.create_unique_constraint('unique_invite', 'invites', ['organization_id', 'user_identifier', 'invited_by'])
    op.create_index(op.f('ix_invites_user_identifier'), 'invites', ['user_identifier'], unique=False)
    op.drop_column('invites', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invites_user_identifier'), table_name='invites')
    op.drop_constraint('unique_invite', 'invites', type_='unique')
    op.create_unique_constraint(op.f('unique_invite'), 'invites', ['organization_id', 'email', 'invited_by'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.drop_column('invites', 'user_identifier')
    # ### end Alembic commands ###
